/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface KeyPair {
  pubKey: Buffer
  privKey: Buffer
}
export function generateKeyPair(): KeyPair
export function calculateSignature(privKey: Buffer, message: Buffer): Buffer
export function verifySignature(pubKey: Buffer, message: Buffer, signature: Buffer): boolean
export function createKeyPair(privKey: Buffer): KeyPair
export function calculateAgreement(pubKey: Buffer, privKey: Buffer): Buffer
export function validatePubKeyFormat(pubKey: Buffer): Buffer
export function hello(): string
